 #ImageDeBase
 FROM java:8  
 COPY . /var/www/java
 WORKDIR /var/www/java
 RUN javac Sample.java
 CMD ["java", "Sample"]

#Ref tutoriel => https://developers.redhat.com/blog/2017/11/17/deploy-java-application-docker/
#

